### ISSUE TITLE
Unable to connect to my Blackfynn account

### ISSUE THREAD

**Issue by DanieleN90** [bvhpatel/SODA#145]
Hi everyone,

I have just created an account on Blackfynn, however when I go on SODA and I insert the key name, API key, and API secret and I click on Add Account nothing happens. I have tried creating three different API keys on Blackfynn but the results on SODA do not change: no message pops up, no accounts get saved, and it's basically as if I did not click the "Add Account" button at all.

**Operating system used:**
Windows 10

**Comment by tramngo1603** [comment]
Hello @DanieleN90, 

Thank you for explaining the issue. Could you please re-launch SODA and perform the same action causing the issue (Connect to Blackfynn). You can then take a screenshot of SODA's Developer Tools (Ctrl+Shift+I or View->Toggle Developer Tools) and kindly attach it here for us or email it directly to sodasparc@gmail.com.

We look forward to examining the issue further.

Thank you very much!

**Comment by tramngo1603** [comment]
Hello @DanieleN90,

Thank you very much for bringing the issue to our attention. We have had the bug fixed in our latest release v2.0.1. Please click [here ](https://github.com/bvhpatel/SODA/releases/download/v2.0.1/SODA-v2.0.1-Windows.exe) to download the Windows installer. We would appreciate it if you could uninstall the older version, install this latest version, and give SODA another try. 

We hope you continue to support SODA and let us know if you encounter any more errors in the future. 

Thank you,
SODA Team
